### ISSUE TITLE
FormatException Bad UTF-8 encoding

### ISSUE THREAD

**Issue by soratobukuroneko** [authpass/authpass#59] opened 2020-03-18 08:22 UTC
Database generated with KeePassXC 2.5.3
works fine with KeepassDX the latest version
but AuthPass 1.50.1025 from play store give me this error when opening the database
`Unknown error while trying to open file. FormatException: Bad UTF-8 encoding 0xb3 (at offset 1)`
![Screenshot_20200318-091448_AuthPass](https://user-images.githubusercontent.com/16183/76939832-6cd0f380-68f9-11ea-832d-10db482d6740.png)

**Comment by hpoul** [comment] 2020-03-18 12:05
@soratobukuroneko thanks for the report. can you please attach log files or send it via email. when launching AuthPass in the top right menu is an option `Email Support` which will create an email with the attached log file.. you can just send it as is (to the entered support@authpass.app address) so I can take a look at it, or send it to yourself if you want to inspect it first..

**Comment by soratobukuroneko** [comment] 2020-03-18 12:33
I also sent it by mail but I upload it there for reference
[app.log](https://github.com/authpass/authpass/files/4348933/app.log)

**Comment by hpoul** [comment] 2020-03-18 12:35
@soratobukuroneko got your log file, thanks. there is a bug when reading the keyfile. am i assuming correctly that your keyfile is simply a binary (not XML or base64)?

**Comment by soratobukuroneko** [comment] 2020-03-18 12:36
yes it's a binary file

**Comment by hpoul** [comment] 2020-03-18 13:53
I have fixed the bug and released 1.5.1 - unfortunately it will take a while until it's available in the play store. It currently shows me "Please expect review times of 7 days or longer."
I'll leave the issue open while waiting for it to be available

**Comment by soratobukuroneko** [comment] 2020-03-18 16:21
Great! Could you release an apk here on GitHub too? So we don't have to wait that much

**Comment by soratobukuroneko** [comment] 2020-03-18 16:23
Also, I don't know if you know about that but your app is also on f-droid. Maybe you could make it released earlier there

**Comment by hpoul** [comment] 2020-03-18 17:44
sure, i've submitted it there ;) i've also created a MR, because new versions require flutter beta version. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6489 although typically fdroid releases also take some time.. (> 2 days usually, while play store releases have been a few hours at most)

(to be honest, i prefer it if people to use the play store version.. it's more reliable, includes dropbox and google drive support and allows me to get better user feedback through google analytics.. so i actually know what features people are struggling with :) )

i'll create a standalone apk .. the problem is in the play store i'm uploading an app bundle, and the play store is generating the actual apk for each device (category) and resigns it with a different signing key, so my apk will not be compatible with the one from the play store.. ie. you can't then simply update from the play store.. but have to reinstall it.. i think i'll create a "github" variant with different package name, so it's clearly separated..

**Comment by hpoul** [comment] 2020-03-18 17:46
btw, in the play store i already see the 1.5.1: https://play.google.com/store/apps/details?id=design.codeux.authpass - so maybe just try to update :-) i guess 99% of play store releases don't go through manually reviews anyway (even if the console still reads "We're currently reviewing your app." 🤦️)

**Comment by soratobukuroneko** [comment] 2020-03-18 18:04
It doesn't complain anymore for the key file but for chacha20 not yet supported x)

**Comment by hpoul** [comment] 2020-03-18 22:44
@soratobukuroneko good point. I've added support, will be in 1.5.2 - again either wait for play store, or i've now created a sideload'able apk [which is built on every commit](https://github.com/authpass/authpass/actions/runs/58499990): https://github.com/authpass/authpass/suites/531037145/artifacts/3090523

**Comment by hpoul** [comment] 2020-03-20 21:54
i'm closing the issue - if you still experience problems in 1.5.2 or 1.5.3, please let me know. thanks

**Closed by hpoul** 2020-03-20 21:54 UTC
