### ISSUE TITLE
Allow copy/pasting to the app from the outside & partial copying

### ISSUE THREAD

**Issue by 0-wHiTeHand-0** [authpass/authpass#127] opened 2020-08-16 07:10 UTC
Hi!
Just another suggestion to improve AuthPass :)
After using it for some weeks, I realized that I can not paste anything from the outside (from a text editor, for example) to the app. I mean, I can't write a password using a text editor, copy it, and paste it into an AuthPass field. This behavior applies to all fields, not just passwords.
Additionally, in AuthPass, I can't copy only a part of the text. For example, if I have a notes field in one entry and I want to copy just a word of my notes, I have to paste the entire text to an editor, and there select what I want.
I think copy/pasting is important for this type of applications.
Thanks!

**Comment by hpoul** [comment] 2020-08-16 09:01
Hi,
Yes, that is true. Unfortunately it seems the copy and paste in flutter is a bit buggy right now. Which platform are you using?
I have also experienced problems on macos, that pasting seems to randomly stop working. I'm not sure this is because of something in AuthPass or if it is a bug in the flutter desktop embedder.

Regarding copying: I've made the shortcut cmd+c/ctrl+c to **always** copy the password (and cmd+b/ctrl+b) to copy the username. I realize this gets in the way of normal copy/pasting.. I'll probably just change the ctrl+c to some other commination.. i just not decided yet on a good combination..

**Comment by 0-wHiTeHand-0** [comment] 2020-08-17 20:24
I'm using OSX.

Good to know the shortcuts. But yeah, this issue is an important handicap to keep in mind, in my opinion.
Thanks,

**Comment by hpoul** [comment] 2020-08-25 21:27
this is now slightly improved in 1.7.5 (already rolling out in the app store):

* When a text field has the focus (e.g. 'Title') has the focus and you press cmd+c - that field is copied *in it's entirety* (no substring copying yet.. I guess this will have to wait another release)
* pressing ESC will unfocus the field
* pressing cmd+c without any entry field in focus (e.g. with the cursor in the search field (cmd+f)) the password will be copied
* cmd+b will still always copy the username

let me know what you think once the release has reached you.

**Comment by hpoul** [comment] 2020-09-10 10:28
fyi - I have now implemented that 

1. when text is actively selected in a field, only the substring will be copied.
2. when the cursor is in a field, but nothing is selected, the entire field is  copied
3. when pressing ESC to unfocus the field, the password will be copied.

![copy-paste](https://user-images.githubusercontent.com/313066/92717551-a6daf980-f360-11ea-81c1-bc75fcd4518a.gif)

i think this should pretty much solve the issue.. occasionally the 'paste' still stops working, but i couldn't quite figure out how this happens.. if somebody has a way to reproduce the paste problems, please let me know.

**Comment by 0-wHiTeHand-0** [comment] 2020-09-11 05:15
Nice, thank you :) I hope you changed your Microsoft password after recording the gif haha

This is gonna be implemented at 1.7.6, right?

**Comment by hpoul** [comment] 2020-09-11 08:51
hehe yeah, I actually checked twice to make sure i'm in the [kdbx file i use for screenshots and testing](https://github.com/authpass/authpass/blob/master/_docs/screenshot_example_company.kdbx) 😅️

it will be in 1.7.7, currently under review.. should be out in a few hours. I've now also published it to github if you don't use the app store variant. (which I would discourage, since the lack of auto updates).

let me know once you've tried 1.7.7.

**Comment by 0-wHiTeHand-0** [comment] 2020-09-11 21:53
Yes, I use the app store's variant because of the auto-updates.

I've tried 1.7.7 right now, and worked like a charm. I see both issues fixed (copying selected text, and pasting text from the outside).
However I also noted inconsistency sometimes when pasting text from outside; sometimes it does not work. But in most cases, it does.

Thank you, good job 👍

**Comment by hpoul** [comment] 2020-09-13 06:30
@0-wHiTeHand-0 thanks for the feedback. I'll close this issue, I've created #141 for the pasting bug. I still have no clue as to when pasting stops working. I'm not sure if it's a bug in AuthPass bug or in Flutter, so I also can't file a bug report for Flutter :-/ It would be nice to have it reproducible.. So if you happen on some scenario were it happens regularly please add it to #141

**Closed by hpoul** 2020-09-13 06:30 UTC
