### ISSUE TITLE
Infinite loading when trying to authenticate to a database on Android

### ISSUE THREAD

**Issue by SneakyShrike** [authpass/authpass#58] opened 2020-03-06 16:07 UTC
For some reason when I plug my usb stick with my keepass database on  into my Android One Plus 5T and try to access my database with this app it  appears to infinitly load on the authentication screen. The blue circular loading animaiton never stops meaning I can never authenticate to gain access to my database. 

I also tried copying my kdbx file to the phones internal storage and acessing it from there but the same occurs. I installed the app from the F-Droid store. 

I'm not sure if this is something on my end or not, or if it's a bug. 

Hopefully this can be resovled as i'm looking foward to trying the app. 

Thanks.

**Comment by hpoul** [comment] 2020-03-07 10:41
Would it be possible for you to try out the version from the play store? I haven't updated the fdroid version yet because I'm using a non released flutter version.. in the newer version would be an option to send log messages by email through the context menu, which could help me debugging the problem.
I guess there is some problem accessing the file

**Comment by SneakyShrike** [comment] 2020-03-08 10:19
> 
> 
> Would it be possible for you to try out the version from the play store? I haven't updated the fdroid version yet because I'm using a non released flutter version.. in the newer version would be an option to send log messages by email through the context menu, which could help me debugging the problem.
> I guess there is some problem accessing the file

I installed the Google play version of the app and I sent you a log file from my email: _gr412@hotmail.co.uk_. However the app seems to freeze and become unresponsive when i try to authenticate, unlike F-Droid that appears to infinitely load. The freezes occur both from a internal phone storage and an external usb stick kdbx file. 

On one occurance the app completey crashed and closed. The crashes / freezes occur as soon as I type in my password and click continue, with the 'save password with biometric key store?' enabled.

**Comment by hpoul** [comment] 2020-05-11 09:29
@SneakyShrike the latest version contains a fixes  re. file loading (namely crashes with a few kdbx files). Could you try if it works for you with the latest version (1.5.7)? thanks.

**Comment by SneakyShrike** [comment] 2020-05-23 10:43
@hpoul I tried version 1.6 on F-Droid and it seems to work now. Thank you for getting back to me.

**Comment by ashed** [comment] 2020-06-03 02:13
Latest version from F-Droid  cannot open local kdbx file.
It is an infinite loading.
And besides password field  hasn't button to view entered chars. It is a little lack of usability.

**Comment by hpoul** [comment] 2020-06-03 06:14
@ashed can you reproduce the problem with a newly created kdbx file which you could share with me, so i can check it out? Otherwise please sind m send me the log file -> in the appbar menu (top right) -> email support - thanks

**Comment by ashed** [comment] 2020-06-05 07:48
> @ashed can you reproduce the problem with a newly created kdbx file which you could share with me, so i can check it out? Otherwise please sind m send me the log file -> in the appbar menu (top right) -> email support - thanks

I am so sorry. Authpass can open my local kbdx v3. But it s-o-o long. Maybe a reason of this is large amount of mapped icons in kbdx?

**Comment by ashed** [comment] 2020-06-05 08:04
Password field hasn't button to view entered chars. It is a little lack of usability.
[keepassdx_view_chars_button](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg3.appinn.net%2Fimages%2F201911%2Fphoto_2019-11-06_16-10-34.jpg!o&f=1&nofb=1)

**Comment by hpoul** [comment] 2020-06-05 08:36
> I am so sorry. Authpass can open my local kbdx v3. But it s-o-o long. Maybe a reason of this is large amount of mapped icons in kbdx?

I wouldn't expect AuthPass to be significantly slower than other clients. Are you loading the file locally or through some cloud storage? You can try sending me your log file after opening your kdbx file, it should contain a few more details about what is taking so long.

**Comment by hpoul** [comment] 2020-06-05 08:38
> Password field hasn't button to view entered chars. It is a little lack of usability.

I've created #86 to track this feature request.

**Comment by hpoul** [comment] 2020-09-19 15:23
If anyone is still experiencing this problem, please reopen. I'll close it in the meantime.
typically the problem is that AuthPass has a pretty slow AES algorithm, so if you have >10k rounds for KDF, it will take *seconds* (and more). I would typically recommend upgrading the database to use argon2, which is 1. at least as secure and 2. implemented using native implementation and faster. 
This is already also possible in AuthPass by clicking on the file in the app bar overflow menu and then select 'Upgrade'.

I'll close this issue, don't hesitate to reopen if you still have this issue.

**Closed by hpoul** 2020-09-19 15:23 UTC
