### ISSUE TITLE
OSX: Using cursor keys while editing causes loss of changes

### ISSUE THREAD

**Issue by abawany** [authpass/authpass#73] opened 2020-05-19 17:25 UTC
I am using v1.6.0 on Catalina. When editing an entry (typically Notes), I will use the cursor key to try to move about within the text box. Unfortunately, this causes the app to move to the next entry and lose my changes to the current entry in the process. Is it possible to modify the context of the cursor keys so that when editing an entry, they allow movement within the entry instead of switching entries pls?

**Comment by hpoul** [comment] 2020-05-19 17:58
this is weird, also when only pressing left/right arrow keys, or only up and down?

(up/down changes the "active" entry to the next/previous one) --- fwiw.. the whole keyboard handling in flutter is still a bit lacking

**Comment by abawany** [comment] 2020-05-19 18:02
left/right appears to behave as expected, i.e. they stay in the text box so the problem appears to be limited to up/down. I figured this was a flutter artifact but thought I would mention it :) .

**Comment by hpoul** [comment] 2020-05-19 18:16
well.. as i mentioned, up/down switches to the next/previous entry in the list.. the problem is, it's not trivial to detect if the cursor is currently in a focused text field.. but that's sure a problem.. maybe i'll find a way..

i'm pretty sure now that linux/windows is slowly progressing towards beta, and the web version maturing as well i'm pretty sure the desktop-awareness of flutter should improve significantly :) (e.g. last week a change got merged in were the mouse cursor will finally change on top of edit boxes or clickable areas ;) looking forward when this makes it into the macos embedder)

**Comment by hpoul** [comment] 2020-08-25 21:19
This took a while :-) but it's now implemented. When a text field is focused and up/down (or command n/p) is pressed, the focus remains in the text field. 1.7.5 is currently rolling out in the mac OS store.
When in a text field is still possible to hit ESC to unfocus the text field and then press up/down to select the next/previous entry.

**Closed by hpoul** 2020-08-25 21:19 UTC

**Comment by abawany** [comment] 2020-08-25 21:21
Thank you very much @hpoul - I appreciate that you fixed this issue and look forward to getting the update when it becomes available to me.
