### ISSUE TITLE
Crash v1.5.5 from webdav

### ISSUE THREAD

**Issue by aTosser** [authpass/authpass#65] opened 2020-05-04 04:51 UTC
The version 1.5.5 added 5/1 on fdroid crashes when opening a database from webdav.

**Comment by hpoul** [comment] 2020-05-04 06:15
Thanks for the report, but can you please give a bit more details.. like: at which stage (connecting webdav, selecting file, entering password), did it work with the previous version? Have you tried copying the kdbx file locally to the device and opening it directly?
Could you provide the log file (under the appbar overflow menu "send email to support" includes the log file), do you see a crash report dialog? As fdroid wouldn't submit the crash report, sending it wouldn't help, but usually there is a "more details" button showing you at least a stack trace?

Thanks

**Comment by aTosser** [comment] 2020-05-04 06:18
Apologies, I was on mobile and just banged out a quick issue. I can connect to the webdav and select the file. The application dies after password entry. The progress spinner will rotate a rotation and some then freeze and the application becomes completely unresponsive requiring a force stop.

**Comment by hpoul** [comment] 2020-05-04 09:50
this is weird, as it actually sounds like a bug which should have been fixed in 1.5.5 (which did not relate to webdav, but any "large" >200kb kdbx file being opened). Have you used 1.5.4 before?
do you know if you are using argon2 kdf?

**Comment by hpoul** [comment] 2020-05-04 10:21
@aTosser I think I found a possible problem, if you are using argon2... i couldn't reproduce the  crash but stumbled upon another problem.. maybe you could give [the latest build](https://github.com/authpass/authpass/actions/runs/95134318) a try (app-sideload-release-1090.apk)

**Comment by hpoul** [comment] 2020-05-10 17:50
since i can't think of any other issue right now which could cause a crash, and 1.5.8 was now released i close the issue.. if you happen to try it again @aTosser please let me know if it works now.. thanks.

**Closed by hpoul** 2020-05-10 17:50 UTC
