### ISSUE TITLE
2FA code generation incorrect

### ISSUE THREAD

**Issue by thomassth** [authpass/authpass#67] opened 2020-05-10 17:33 UTC
Been using KeePass2Android for all my 2FA codes. 
Tried to open the same vault in AuthPass and found none of the 2FA codes are correct. Tried on Github Facebook and other major sites.
The vault is in kdbx 4 if that matters? Not sure
Can't screenshot or give my code out for obvious reasons, unless someone can make a dummy 2fa testing site

**Comment by hpoul** [comment] 2020-05-10 17:46
this is weird, because i've tried multiple sites and they worked. (and I know of others using it as well).. I can only imagine that AuthPass might not detect the parameters correctly how KeePass2Android stores them in the password entry.. (there is no "standard" for how those parameters are stored, each keepass app seems to do it differently).. 
if you've got some time you could try creating a new kdbx database with keepass2android and add a totp token from a dummy generator like https://www.xanxys.net/totp/ .. and compare the generated tokens between authpass and keepass2android.. or entering the secret into e.g. https://totp.danhersam.com/ should make it possible to verify the tokens..
if it doesn't work i could use that kdbx file to reproduce the bug.

**Comment by thomassth** [comment] 2020-05-10 18:04
I built my vault like this
(Via KeeWeb)
Field: otp
Entry: otpauth://totp/default?secret=[text from any kind of QR code]

Just tested on Mega.nz
KeeWeb passed, AuthPass failed

**Comment by thomassth** [comment] 2020-05-10 18:16
Just noticed that the "Last modified" is strangely set to exactly 7 days into the future.
The entry I just added is modified at May 18th.

**Comment by hpoul** [comment] 2020-05-10 18:56
@thomassth i honestly can't think of any reason for that 7 days difference.
I have just tried it myself.. with https://rootprojects.org/authenticator/ .. i have created a kdbx file with keeweb, saved it, and opened it with AuthPass.. both show me the exact same code (and same modified timestamp for that matter)

<img width="944" alt="Screenshot 2020-05-10 at 20 53 53" src="https://user-images.githubusercontent.com/313066/81507888-a83bdd00-9300-11ea-9f30-68e0628bfc29.png">

**Comment by hpoul** [comment] 2020-05-10 18:57
and here keeweb vs authpass, looks good to me:

<img width="708" alt="Screenshot 2020-05-10 at 20 56 49" src="https://user-images.githubusercontent.com/313066/81507911-cd305000-9300-11ea-8550-a0cf33749548.png">

**Comment by hpoul** [comment] 2020-05-10 18:58
btw. on which platform are you using AuthPass?

**Comment by thomassth** [comment] 2020-05-10 19:38
Android 10 (Samsung One UI 2.1)

I too noticed the 2FA seems functioning IF you added it from AuthPass. Any otp added elsewhere THEN bring into AuthPass fails.

More on the time thing: Not only any entry modified on AuthPass had a future "modified on" date, they also had a future "created on" date; both KeePass2Android and KeePassDX throws error and cannot open the vault. Luckily Keeweb took it quite well and I was able to fix things there. 

If some other people had this problem it warrants a separate issue.

**Comment by thomassth** [comment] 2020-05-10 20:11
BTW It seems the date bug does not exist on your side. Are you on emulator or on a newer (debug) version?
I'm on 1.5.8+1106 FYI

I've deleted and redownloaded the app from Play Store for the following test.
Another test: Added another test otp with my other otps in Keeweb. Moved to AuthPass. Compare the keys generated on both sides.
**The new key works, but other old keys does not.** All keys are set with the same preset I mentioned. The only difference I can think of is the date of creation.

For the last test of tonight I made a new vault in AuthPass, moved it to my Mac so I can see the result in KeeWeb
KeeWeb unlocked my file at first but cannot get into the vault proper. It went to the pref menu and showed some error on history size. 
After some more tinkering I can't even get KeeWeb to unlock my vault. If this is my main vault I would be furious.

![image](https://user-images.githubusercontent.com/8331853/81509111-02f22a80-933b-11ea-9d56-4aedb1a090ba.png)

**Comment by hpoul** [comment] 2020-05-10 20:29
ah okay, you meant the passwords created and modified with AuthPass had the wrong date.. i thought timestamps imported from keeweb were displayed wrong.
at least that's an easy one.. there was a problem with the date format when storing date/time strings into the database.. (and there is even a second problem with date/time strings.. )

unfortunately this can't be related with the TOTP problem.. any chance you could reproduce the problem with a new database and non-confidential totp (like one generated with https://rootprojects.org/authenticator/ )

**Comment by hpoul** [comment] 2020-05-11 10:21
@thomassth i wanted to try out adding a TOTP key with keepass2android, but discovered it does not even support this.. how did you originally add your secret keys to your entries?

**Comment by thomassth** [comment] 2020-05-11 11:16
Manually
KP2A don't have a specific UI but when you add things properly it gives the code just fine

**Comment by hpoul** [comment] 2020-05-11 11:20
I guess there must be something different in the format, can't think of anything else.. the only way for me to fix it, is to get a reproduce able kdbx..
Have you tried if you can somehow get the bug with secrets from https://rootprojects.org/authenticator/ ?

**Comment by thomassth** [comment] 2020-05-12 19:52
This bug is way trickier than I thought

A few findings so far:
1. Old 2FAs affected, new ones are fine, even within the same vault
2. Also noted are the wrong date/time of Last Modified:
If I did it at morning, the date is in the past
If I did it late at night (eg. 3AM) the date are in the future

I have no idea if any of these are related. 
Can't find a way to reproduce old 2FA part of the bug without using my own 2FAs
Here is one I made with future modified time

PW: lolwtf
(can't find where to change the vault password so there's that)
[AuthTest.kdbx.zip](https://github.com/authpass/authpass/files/4618094/AuthTest.kdbx.zip)

**Comment by hpoul** [comment] 2020-05-12 20:02
the wrong modification time should already be fixed in the latest version.. it was just a [dumb serialization bug](https://github.com/authpass/kdbx.dart/commit/aa115f16a491be163fea394dd0d1f5cd308b54ef#diff-27a6539dbbb5dda2454d7ca9d5fcb1aeR222-R226).. 

well there shouldn't be any difference between "old" totp and new ones :) are there any differences in the parameters? like number of digits, or seconds valid, ...?

**Comment by hpoul** [comment] 2020-05-12 20:03
(re time stamp: not latest version, latest commit/build.. it's not yet released)

**Comment by thomassth** [comment] 2020-05-12 20:19
Just noticed among my 2FAs, Google and FB are correct all along, but GitHub, mega.nz etc aren't
And I just tried rebuilding the whole vault, only bringing otp keys out, the results are the same
This is getting more and more puzzling

**Comment by thomassth** [comment] 2020-05-12 20:27
I think I cracked the case!
not every 2FAs have the same key length
Google and FB: 32 char
AMazon: 52 char
GitHub: 16 char
If I change my Amazon code to 32 char, KeeWeb gets the same (wrong) key as AuthPass

**Comment by hpoul** [comment] 2020-05-12 22:13
yeah, but that has to be configured somehow.. if you tell me how it's configured for keepass2android or whatever i can add support for it.. in AuthPass you could also just add &digits=XXX to the uri and it should work exactly the same..

**Comment by hpoul** [comment] 2020-05-12 22:15
err.. wait a second.. i didn't quite understand what you meant.. i thought digits of the token.. but you mean the length of the secret?

**Comment by hpoul** [comment] 2020-05-12 22:41
fyi.. if you mean the characters of the secret, it probably means you set the &algorithm= to:

* sha512 for 64 bytes = ~103 base32 characters
* sha256 for 32 bytes = 52 base32 characters
* sha1 (the default, so can be omitted.. those should work) for 20 bytes = 32 base32 characters

not sure about github.. maybe it's base64 encoded secret, not base32?

**Comment by thomassth** [comment] 2020-05-14 14:25
I was trying to say the length of secret of the otpauth [(This part)](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#secret)

In other words I was talking about the word count in`?secret=`part, not the `&digits=` part

Just noticed about the `&algorithm=` part, I didn't use it, but apparently not even Google follows it, and I guess most other KeePass apps don't care as well. Just count the char length and apply the algorithm accordingly? I'm not sure what other apps have done here

**Comment by hpoul** [comment] 2020-05-14 17:00
this is weird, afaik google basically always uses sha1, because it's the default for the authenticator app: https://github.com/google/google-authenticator/wiki/Key-Uri-Format#algorithm

hmm.. is the amazon token with SHA1 in authpass correct?

**Comment by hpoul** [comment] 2020-05-15 09:32
@thomassth maybe you could give this one a try: https://github.com/authpass/authpass/actions/runs/105524571 it disabled secret padding in the underlying library..

tbh, i do not think padding is part of the [TOTP RFC](https://tools.ietf.org/html/rfc6238), it was implemented by the [node.js otplib library](https://www.npmjs.com/package/otplib#length-of-secrets) and the dart library i'm using seems to be based on that.. but i did not find any mention anywhere else.. so i'm not sure how common secret padding for TOTP dokens is..

**Comment by thomassth** [comment] 2020-05-15 15:32
> @thomassth maybe you could give this one a try: https://github.com/authpass/authpass/actions/runs/105524571 it disabled secret padding in the underlying library..
> 
> tbh, i do not think padding is part of the [TOTP RFC](https://tools.ietf.org/html/rfc6238), it was implemented by the [node.js otplib library](https://www.npmjs.com/package/otplib#length-of-secrets) and the dart library i'm using seems to be based on that.. but i did not find any mention anywhere else.. so i'm not sure how common secret padding for TOTP tokens is..

Nope not fixed

Can you try to replicate the issue on your side? Try adding and using Github, MS, Amazon and other 2FA with non-32 char long secrets

It's not ideal keep going back and forth like this

**Comment by hpoul** [comment] 2020-05-16 14:50
there was a bug in the otp library that the padding stuff was not correctly disabled: https://github.com/Daegalus/dart-otp/pull/20 i've fixed it now and also verified that e.g. github worked.. maybe you can give this one another try https://github.com/authpass/authpass/actions/runs/106577363

btw. did the QR code reader work for you? it seems there was something wrong with the camera permissions :-/ this should be fixed now as well..

**Comment by thomassth** [comment] 2020-05-16 15:25
I think you nailed it mate

Both Amazon (super long) and GitHub (very short) 2FA works now

And I thought you just never had the camera feature in the first place lol that's working fine too

**Comment by hpoul** [comment] 2020-05-17 09:13
great, thanks for testing :-) will be part of the next release, within a week probably. I'll close the issue, if there is anything else feel free to open another one :)

**Closed by hpoul** 2020-05-17 09:13 UTC
Labels: bug
